// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegurosLafise.Api.Data;

#nullable disable

namespace SegurosLafise.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegurosLafise.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "juan.perez@correo.com",
                            Identificacion = "001-200390-1001X",
                            Nombre = "Juan Perez"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "maria.lopez@correo.com",
                            Identificacion = "001-150585-1002Y",
                            Nombre = "Maria Lopez"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "carlos.ramirez@correo.com",
                            Identificacion = "001-100777-1003Z",
                            Nombre = "Carlos Ramirez"
                        });
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.Cobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MontoCobertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Coberturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MontoCobertura = 15000m,
                            Nombre = "Robo Total"
                        },
                        new
                        {
                            Id = 2,
                            MontoCobertura = 8000m,
                            Nombre = "Choque y Colision"
                        },
                        new
                        {
                            Id = 3,
                            MontoCobertura = 5000m,
                            Nombre = "Responsabilidad Civil"
                        },
                        new
                        {
                            Id = 4,
                            MontoCobertura = 6000m,
                            Nombre = "Danos a Terceros"
                        },
                        new
                        {
                            Id = 5,
                            MontoCobertura = 1000m,
                            Nombre = "Asistencia en Carretera"
                        });
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.Poliza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("PrimaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SumaAsegurada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroPoliza")
                        .IsUnique();

                    b.HasIndex("VehiculoId");

                    b.ToTable("Polizas");
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.PolizaCobertura", b =>
                {
                    b.Property<int>("PolizaId")
                        .HasColumnType("int");

                    b.Property<int>("CoberturaId")
                        .HasColumnType("int");

                    b.HasKey("PolizaId", "CoberturaId");

                    b.HasIndex("CoberturaId");

                    b.ToTable("PolizaCoberturas");
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("ValorComercial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.Poliza", b =>
                {
                    b.HasOne("SegurosLafise.Api.Models.Cliente", "Cliente")
                        .WithMany("Polizas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegurosLafise.Api.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.PolizaCobertura", b =>
                {
                    b.HasOne("SegurosLafise.Api.Models.Cobertura", "Cobertura")
                        .WithMany("PolizaCoberturas")
                        .HasForeignKey("CoberturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegurosLafise.Api.Models.Poliza", "Poliza")
                        .WithMany("PolizaCoberturas")
                        .HasForeignKey("PolizaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobertura");

                    b.Navigation("Poliza");
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.Cliente", b =>
                {
                    b.Navigation("Polizas");
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.Cobertura", b =>
                {
                    b.Navigation("PolizaCoberturas");
                });

            modelBuilder.Entity("SegurosLafise.Api.Models.Poliza", b =>
                {
                    b.Navigation("PolizaCoberturas");
                });
#pragma warning restore 612, 618
        }
    }
}
